//! 번역문을 JSON 원문에 적용한다.
//!
//! 파일을 다시 직렬화하지 않고 대상 문자열 값의 바이트 구간만 교체하므로
//! 번역하지 않은 부분은 원본과 바이트 단위로 동일하게 유지된다.
//!
//! 경로에 jsonspan::NESTED 토큰이 있으면 바깥 문자열 값을 JSON으로 파싱해 안쪽을 같은 방식으로
//! 교체한 뒤, 그 결과를 다시 문자열로 인코딩해서 바깥 값을 교체한다. (플러그인 파라미터)

use std::collections::{BTreeMap, HashSet};

use crate::jsonspan::{self, NESTED};

use super::plugins_js;

pub struct PatchResult {
    pub text: String,
    pub applied: usize,
    /// 경로를 찾지 못했거나 문자열이 아니어서 건너뛴 포인터
    pub skipped: Vec<String>,
}

/// RPG Maker(JSON.stringify)와 같은 방식으로 문자열을 JSON 리터럴로 만든다.
/// 비ASCII 문자는 이스케이프하지 않는다.
fn to_json_string(s: &str) -> String {
    serde_json::to_string(s).expect("문자열 직렬화는 실패하지 않음")
}

/// 파일 종류에 맞게 적용한다. js/plugins.js는 `$plugins` 배열 부분만 JSON으로 다룬다.
pub fn patch_file(file: &str, src: &str, patches: &[(String, String)]) -> Result<PatchResult, String> {
    if !file.ends_with(".js") {
        return patch(src, patches).map_err(|e| e.to_string());
    }
    let range = plugins_js::json_range(src).ok_or("$plugins 배열을 찾을 수 없습니다.")?;
    let inner = patch(&src[range.clone()], patches).map_err(|e| e.to_string())?;
    let mut text = src.to_string();
    text.replace_range(range, &inner.text);
    Ok(PatchResult { text, ..inner })
}

pub fn patch(src: &str, patches: &[(String, String)]) -> Result<PatchResult, jsonspan::ParseError> {
    let root = jsonspan::parse(src)?;
    let mut spans = Vec::with_capacity(patches.len());
    let mut skipped = Vec::new();
    let mut applied = 0;
    // 중첩 경로는 바깥 문자열 경로별로 모아서 한 번에 처리한다
    let mut nested: BTreeMap<&str, Vec<(String, String)>> = BTreeMap::new();
    let mut direct = HashSet::new();

    for (pointer, text) in patches {
        if let Some((outer, inner)) = jsonspan::split_nested(pointer) {
            nested.entry(outer).or_default().push((inner.to_string(), text.clone()));
            continue;
        }
        match root.pointer(pointer) {
            Some(node) if node.as_str().is_some() => {
                direct.insert(pointer.as_str());
                spans.push((node.start, node.end, to_json_string(text)));
                applied += 1;
            }
            _ => skipped.push(pointer.clone()),
        }
    }

    for (outer, inner_patches) in nested {
        let rejoin = |p: &str| format!("{outer}/{NESTED}{p}");
        let node = root.pointer(outer).filter(|n| n.as_str().is_some());
        // 바깥 문자열 자체를 통째로 바꾸는 패치가 있으면 그쪽을 우선한다
        let result = match node {
            Some(n) if !direct.contains(outer) => patch(n.as_str().unwrap_or_default(), &inner_patches).ok().map(|r| (n, r)),
            _ => None,
        };
        let Some((node, result)) = result else {
            skipped.extend(inner_patches.iter().map(|(p, _)| rejoin(p)));
            continue;
        };
        skipped.extend(result.skipped.iter().map(|p| rejoin(p)));
        if result.applied > 0 {
            spans.push((node.start, node.end, to_json_string(&result.text)));
            applied += result.applied;
        }
    }

    // 뒤에서부터 교체해야 앞쪽 오프셋이 유지된다
    spans.sort_by(|a, b| b.0.cmp(&a.0));
    spans.dedup_by_key(|s| s.0);
    let mut text = src.to_string();
    for (start, end, replacement) in &spans {
        text.replace_range(start..end, replacement);
    }
    Ok(PatchResult { text, applied, skipped })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn keeps_untouched_bytes() {
        let src = "[\nnull,\n{\"id\":1,\"name\":\"ハロルド\",\"note\":\"<x:1.50>\",\"v\":1.50}\n]";
        let r = patch(src, &[("/1/name".into(), "하롤드 \"\\".into())]).unwrap();
        assert_eq!(r.applied, 1);
        assert_eq!(r.text, "[\nnull,\n{\"id\":1,\"name\":\"하롤드 \\\"\\\\\",\"note\":\"<x:1.50>\",\"v\":1.50}\n]");
    }

    #[test]
    fn nested_strings() {
        let inner = r#"[{"Name":"回復","Id":"3"},{"Name":"攻撃","Id":"4"}]"#;
        let note = serde_json::to_string("一行目\n二行目").unwrap();
        let src = serde_json::json!({ "List": inner, "Help": note, "Size": "28" }).to_string();
        let r = patch(
            &src,
            &[
                ("/List/~j/1/Name".into(), "공격".into()),
                ("/Help/~j".into(), "첫 줄\n둘째 줄".into()),
                ("/List/~j/5/Name".into(), "없음".into()),
            ],
        )
        .unwrap();
        assert_eq!(r.applied, 2);
        assert_eq!(r.skipped, ["/List/~j/5/Name"]);
        let v: serde_json::Value = serde_json::from_str(&r.text).unwrap();
        assert_eq!(v["List"], r#"[{"Name":"回復","Id":"3"},{"Name":"공격","Id":"4"}]"#);
        assert_eq!(v["Help"], serde_json::to_string("첫 줄\n둘째 줄").unwrap());
        assert_eq!(v["Size"], "28");
    }

    #[test]
    fn plugins_js_wrapper() {
        let src = "// Generated by RPG Maker.\nvar $plugins =\n[\n{\"name\":\"A\",\"status\":true,\"parameters\":{\"T\":\"文字\"}}\n];\n";
        let r = patch_file("www/js/plugins.js", src, &[("/0/parameters/T".into(), "글자".into())]).unwrap();
        assert_eq!(r.applied, 1);
        assert_eq!(r.text, src.replace("文字", "글자"));
    }
}
