//! js/plugins.js 처리.
//!
//! 파일 형식은 `var $plugins =\n[\n{...},\n...\n];` 형태의 JS지만
//! 배열 부분은 그대로 JSON이므로 그 구간만 잘라서 JSON으로 다룬다.

use std::ops::Range;

/// `$plugins` 배열 리터럴의 바이트 구간
pub fn json_range(src: &str) -> Option<Range<usize>> {
    let var = src.find("$plugins")?;
    let start = var + src[var..].find('[')?;
    let end = src.rfind(']')? + 1;
    (end > start).then_some(start..end)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn finds_array() {
        let src = "// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n{\"name\":\"A\"}\n];\n";
        let r = json_range(src).unwrap();
        assert_eq!(&src[r], "[\n{\"name\":\"A\"}\n]");
    }
}
